### ISSUE TITLE
Unable to add multiple Placemarks

### ISSUE THREAD

**Issue by nickpasko** [urbancamo/javaapiforkml#11]
Just a single Feature is supported, so there is no way to create a KML with several PlaceMarks.

**Comment by polarene** [comment]
I managed to add several PlaceMarks by adding them to a Folder.

**Comment by mischah** [comment]
Sorry, this project is not actively maintained :pensive:

See #18 for further information.

**Comment by urbancamo** [comment]
As mentioned above, this isn't an issue (any more). Multiple placemarks can be added to a folder
