### ISSUE TITLE
Handle to FileOutputstream not closed in Kml.marshal

### ISSUE THREAD

**Issue by ericali78** [urbancamo/javaapiforkml#14]
It seems that it occurs in Kml.marshal(File ..) impl : 

/**
     \* Java to KML
     \* The object graph is marshalled to a File object.
     \* The object is not saved as a zipped .kmz file.
     \* @see marshalKmz(String, Kml...)
     \* 
     */
    public boolean marshal(final File filename)
        throws FileNotFoundException
    {
        OutputStream out = new FileOutputStream(filename);
        return this.marshal(out);
    }

**Comment by ZiglioUK** [comment]
what about
    this.marshal(out);
    out.close();

**Comment by mischah** [comment]
Sorry, this project is not actively maintained :pensive:

See #18 for further information.

**Comment by laubfall** [comment]
Fixed in the xjc plugin.
