### ISSUE TITLE
Usage of outdated jaxb

### ISSUE THREAD

**Issue by hestad** [urbancamo/javaapiforkml#15]
jaxb was included in jdk6+, very annoying dependency!

<groupId>com.sun.xml.bind</groupId>
<artifactId>jaxb-impl</artifactId>

**Comment by ZiglioUK** [comment]
Have you tried excluding that dependency in your POM?

**Comment by hestad** [comment]
Yes, but the jdk package name is a bit different. Another solution is to make a minified wrapper.

**Comment by hestad** [comment]
I see two problems with this upgrade:
1)NotNull is used (now com.sun.istack.internal.NotNull). It can be replaced with javax.annotation or some other. See http://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use
2)NamespacePrefixMapper is used (now com.sun.xml.internal.bind.marshaller.NamespacePrefixMapper). See: https://issues.apache.org/jira/browse/SIS-74

In the meantime, accepting the jaxb 2.2.4... PR should be better than what is now.

**Comment by mischah** [comment]
Sorry, this project is not actively maintained :pensive:

See #18 for further information.

**Comment by urbancamo** [comment]
Fixed now in v3.x.x
