### ISSUE TITLE
Defining GroundOverlay using LatLonQuad

### ISSUE THREAD

**Issue by jmcazaux** [urbancamo/javaapiforkml#20]
Hi guys,
I understand the project is currently changing hands, but I have a question and would greatly appreciate some help.

I am using JavaAPIForKML as a bridge between systems and at some point I need to have GroundOverlays defined with LatLonQuad.

Apparently once cannot create an overlay with LatLonQuad (LatLonBox is required), but if I convert LatLonBox to LatLonQuad in Gooogle Earth, would JavaAPIForKML be able to read the converted KML ?

Many thanks for your help,
JM

**Comment by laubfall** [comment]
Hi JM,
do you have a sample KML that makes use of a LatLonQuad?

Javaapiforkml was able to read the following sample:

```
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xal="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:gx="http://www.google.com/kml/ext/2.2">
    <GroundOverlay>
        <drawOrder>0</drawOrder>
        <altitude>0.0</altitude>
        <LatLonBox>
            <north>0.0</north>
            <south>0.0</south>
            <east>0.0</east>
            <west>0.0</west>
            <rotation>0.0</rotation>
        </LatLonBox>
        <gx:LatLonQuad>
            <coordinates>3.0,4.0 3.0,6.0 3.0,7.0</coordinates>
        </gx:LatLonQuad>
    </GroundOverlay>
</kml>
```

The resulting Kml Object contained the LatLonQuad in the field groundOverlayObjectExtension.

Daniel

**Comment by jmcazaux** [comment]
Hi Daniel,
sorry, but in the end I did not use LatLonQuad...

**Comment by jmcazaux** [comment]
Vous avez du GPS qui bouge ?

**Comment by laubfall** [comment]
A moving GPS? No.

Can i close this issue?

**Comment by jmcazaux** [comment]
Hi Daniel, sorry the comment above did not belong here (typed in the wrong window).

Yes, the issue can be closed.
