### ISSUE TITLE
can't use it in Android cause Jaxb

### ISSUE THREAD

**Issue by fly7632785** [urbancamo/javaapiforkml#21]
I can't use this library in android by gradle.
Cause Javaapiforkml use Jaxb, and Jaxb can't be used in android for its core libraries can't be replaced.
See:

![234b5bc280986aa6747b70a4541614b8](https://user-images.githubusercontent.com/10276266/32091385-83707e04-bb26-11e7-9ce5-8141a27f680f.jpg)

**Comment by laubfall** [comment]
Hi!

First of all i want to say that javaapiforkml was never be meant to be used in an android environment and we do not have any plans actually to make things work with android.

I'm not that deep into android programming but it seems to me that android complains cause of the namespace javax that is protected (means you are not allowed to include classes from this package). On Stackoverflow i found multiple threads to this issue and some possible solutions. One solution was to use the JarJar tool that was also be mentioned in the message you shown here.

https://stackoverflow.com/questions/5461127/using-jaxb-with-google-android

Greetings,
Daniel

**Comment by urbancamo** [comment]
No plans to fix this - please re-raise if you still require this looked at.
