### ISSUE TITLE
Failed logging during maven build

### ISSUE THREAD

**Issue by laubfall** [urbancamo/javaapiforkml#22]
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
log4j:ERROR [java.net.URLClassLoader@759fad4] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [org.jvnet.jaxb2.maven2.ParentFirstClassLoader@77307458].
log4j:ERROR Could not instantiate appender named "stdout".

**Comment by urbancamo** [comment]
No longer an issue
