### ISSUE TITLE
Support for gx:Track

### ISSUE THREAD

**Issue by tbsalling** [urbancamo/javaapiforkml#3]
<gx:Track> is an extension of the OGC KML 2.2 standard and is supported in Google Earth 5.2 and later.

Read more: https://developers.google.com/kml/documentation/kmlreference#gxtrack.

A feature request is to support <gx:Track> in javaapiforkml.

**Comment by ZiglioUK** [comment]
Try this https://github.com/flevine100/JavaAPIForKML-DELETE/tree/gxtrack/src/main/java/de/micromata/opengis/kml/v_2_2_0/gx

**Comment by ZiglioUK** [comment]
@flevine100, please consider a pull request

**Comment by flevine100** [comment]
I thought that DELETE repo was dead - are all the changes needed for the pull request in:
https://github.com/flevine100/javaapiforkml/tree/gxtrack - that's the one that was forked off of macromedia's github repo.  The other one was a direct import of SVN and didn't have the tracking info back to macromedia.

**Comment by ZiglioUK** [comment]
You're right @flevine100, I've just sent a pull request myself from the repo you linked to, let's see what happens

https://github.com/micromata/javaapiforkml/pull/4

**Comment by tbsalling** [comment]
Thank you for pointing me to @flevine100 's forked repo! Very useful. I will have a closer look.

**Comment by unterstein** [comment]
Hi, thank you very much for your pull-request. We just merged your changes.

**Comment by tbsalling** [comment]
This is great. Thank you. Is there any chance you could release the merged version to maven central? I guess only Micromata is privileged to do so?

**Comment by flevine100** [comment]
Definitely not going to publish anything to Maven Central.  Macromedia merged the pull request, so you can ask them. In the meantime you'll need to build it yourself.

**Comment by tbsalling** [comment]
Well, it _was_ Micromata I asked. But never mind that. 

Instead I have forked their repository with the merged gx:track support from @flevine100 and published the compiled jar on Maven Central.

Forked repo:
https://github.com/tbsalling/javaapiforkml

Maven central:
http://search.maven.org/#artifactdetails%7Cdk.tbsalling%7CJavaAPIforKml%7C2.2.0.1%7Cjar

**Comment by unterstein** [comment]
Hey there,

we are working on it. We wanted to publish the artifact with the same group id as it was published before, but run into trouble of ownership with the publishing rights of this artifact on maven central ... But never mind. We will solve this issue and publish the artifact with the correct group id soon.

Kind regards,
Johannes

**Comment by tbsalling** [comment]
I didn't know. But that sounds good, and I'll be looking forward to the release.

**Comment by unterstein** [comment]
Hi Thomas,

thank you very much for your engagement. Today we published the version 2.2.1, which should be pretty the same as your release.

See: http://search.maven.org/#artifactdetails%7Cde.micromata.jak%7CJavaAPIforKml%7C2.2.1%7Cjar

Happy hacking!

**Comment by tbsalling** [comment]
That's great. Thank you. I will use it. Unfortunately, I don't think I can demote or delete my own release from Maven Central.
