### ISSUE TITLE
Decouple from glassfish

### ISSUE THREAD

**Issue by kristofdho** [urbancamo/javaapiforkml#34]
Currently, the glassfish JAXB implementation is included as dependency while 99% of the project only depends on jakarta.
Only the `Kml` class itself uses it for a beautifier feature:
https://github.com/micromata/javaapiforkml/blob/36e63335cf8642e20d990a414134677c06a5e536/src/main/java/de/micromata/opengis/kml/v_2_2_0/Kml.java#L944-L945

We use this library together with eclipselink moxy to fix issues with CDATA handling: https://code.google.com/archive/p/javaapiforkml/issues/37

Ideally this could be converted to a bring-your-own-implementation library. The tests can still rely on jaxb, and they could even be expanded to test against different implementations altough not really required because they all should handle the jakarta API appropriately.

To not break backwards compatibility, if that's even a concern, there could be a split between modules where a core module provides all models with just a dependency to jakarta.
The current released module could then have a dependency on glassfish and the core module.

**Comment by urbancamo** [comment]
The beautifier definitely needs replacing, and as of v3.0.7 has been removed from Kml.java, awaiting a new implementation.

```java
public static String prettyPrintByTransformer(String xmlString, int indent, boolean ignoreDeclaration) {

    try {
        InputSource src = new InputSource(new StringReader(xmlString));
        Document document = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(src);

        TransformerFactory transformerFactory = TransformerFactory.newInstance();
        transformerFactory.setAttribute("indent-number", indent);
        Transformer transformer = transformerFactory.newTransformer();
        transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
        transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, ignoreDeclaration ? "yes" : "no");
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");

        Writer out = new StringWriter();
        transformer.transform(new DOMSource(document), new StreamResult(out));
        return out.toString();
    } catch (Exception e) {
        throw new RuntimeException("Error occurs when pretty-printing xml:\n" + xmlString, e);
    }
}
```

one suggestion would be to use a custom beautifier, like the one above, but I'm conscious of the CDATA handling issue mentioned above - no idea whether this has become an issue again with the removal of the glassfish NamespacePrefixer?

**Comment by urbancamo** [comment]
I believe we are doing the right thing now with the dependency on org.glassfish.jaxb > jaxb-runtime as the configured runtime instance of JAXB. @kristofdho please review the current source code and dependencies. I've not had any issues with CDATA sections being formatted incorrectly. If I don't hear back I'll close this issue in due course.

**Comment by urbancamo** [comment]
Closed as believed fixed

**Comment by kristofdho** [comment]
I haven't had time to look into the update yet.
This can stay closed for now, I'll let you know if there is anything further.
