### ISSUE TITLE
JAK creating malformed KML

### ISSUE THREAD

**Issue by SriramMLN** [urbancamo/javaapiforkml#9]
The KML generated by JAK is malformed in Schema validation with ogckml22.xsd due to refreshInterval, viewRefreshTime and viewBoundScale all three set to 0.0 by default in <icon> element. This issue is reported only for <Icon> under <IconStyle>.
All three variables are from de.micromata.opengis.kml.v_2_2_0.Icon Java class.
Analysed the Icon class and found the issue was due to declaration of refreshInterval, viewRefreshTime and viewBoundScale all as primitive double.
Changing the data type from primitive to Double wrapper fixes the issue but not sure on other impacted areas. Performed a call hierarchy on these three getters and setters and there are no impact in other classes except Icon, example and JUnit tests.
Please validate my findings and will be great if a new code is released with this fix.
KML Fragment:
 <Style id="pushpin">
            <IconStyle id="myIcon">
                <scale>0.0</scale>
                <heading>0.0</heading>
                <Icon>
                    <href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
                    <refreshInterval>0.0</refreshInterval>
                    <viewRefreshTime>0.0</viewRefreshTime>
                    <viewBoundScale>0.0</viewBoundScale>
                </Icon>
            </IconStyle>
        </Style>

**Comment by mischah** [comment]
Sorry, this project is not actively maintained :pensive:

See #18 for further information.

**Comment by urbancamo** [comment]
I'll look into this issue...

**Comment by urbancamo** [comment]
This was fixed via PR from SriramMLN on 20/08/2022.
